runtime: nodejs22

service: phoga-back-office

handlers:
  - url: /
    static_dir: dist/back-office/browser

  # Catch-all rule to serve index.html for any path not matched above
  - url: /.*
    static_files: dist/back-office/browser/index.html
    upload: dist/back-office/browser/index.html
