runtime: nodejs22

service: phoga-back-office

handlers:
  # Serve index.html for the root URL ('/')
  - url: /dist/back-office/browser/
    static_files: index.html
    upload: index.html
    secure: always
    redirect_http_response_code: 301

  # Serve CSS files from the root 'dist/back-office/browser/' directory
  - url: dist/back-office/
    static_folder: /browser
    upload: /browser
