runtime: nodejs22

service: phoga-back-office

handlers:
  # Serve index.html for the root URL ('/')
  - url: /
    static_files: dist/back-office/browser/index.html
    upload: dist/back-office/browser/index.html

  - url: /
    static_dir: dist/back-office/browser/
