runtime: nodejs22

handlers:
  - url: /
    static_files: dist/back-office/browser/index.html
    upload: dist/back-office/browser/index.html
    mime_type: text/html

  # Serve CSS files from the root 'dist/back-office/browser/' directory
  - url: /(.+)\.css
    static_files: dist/back-office/browser/\1.css
    upload: dist/back-office/browser/.+\.css
    mime_type: text/css

  # Serve JavaScript files from the root 'dist/back-office/browser/' directory
  - url: /(.+)\.js
    static_files: dist/back-office/browser/\1.js
    upload: dist/back-office/browser/.+\.js
    mime_type: text/javascript

  # Serve HTML files from the root 'dist/back-office/browser/' directory
  - url: /(.+)\.html
    static_files: dist/back-office/browser/\1.html
    upload: dist/back-office/browser/.+\.html
    mime_type: text/html

  # Catch-all rule to serve index.html for any path not matched above
  - url: /.*
    static_files: dist/back-office/browser/index.html
    upload: dist/back-office/browser/index.html
