steps:
  # Install
  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  # Build
  - name: "node"
    entrypoint: "npm"
    args: ["run", "build:bo:stage"]

  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=stage"]
options:
  logging: CLOUD_LOGGING_ONLY
