steps:
  # Install
  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  # Build
  - name: "node"
    entrypoint: "npm"
    args: ["run", "build:client:staging"]

  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--appyaml=app-client.yaml", "--version=staging"]

options:
  logging: CLOUD_LOGGING_ONLY
