name: client
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install dependencies
        run: npm ci
      - name: Test and coverage
        run: npm run test:client:ci
      # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/6
      - name: Fix code coverage paths
        working-directory: /home/runner/work/phoga-front/phoga-front/coverage/client
        run: |
          sed -i 's|projects/client/src/|/home/runner/work/phoga-front/phoga-front/projects/client/src/|g' lcov.info
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
        with:
          projectBaseDir: projects/client/
